name: Notion 뉴스봇

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 오전 9시 (UTC 기준)
  workflow_dispatch:

jobs:
  run-news-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python 설치
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: 의존성 설치
        run: pip install requests beautifulsoup4
      - name: 뉴스 등록 실행
        run: python notion_news.py
